csv_path: "./challenge_set/challenge_set.csv"  ## path to the csv file containing images' url and captions
image_path: "url" ##"./challenge_set/" ## determining retriving images from the network using provided urls or reading from the loacl drive
use_cuda: true ## using GPU 
pretrained_model: "openai/clip-vit-base-patch32" ## the pretrained CLIP model. can be set with other options as well.


